### ISSUE TITLE
Alt_id terms not being obsoleted in update

### ISSUE THREAD

**Issue by dustine32** [pantherdb/fullgo_paint_update#12]
Term GO:0005554 is an alt_id in the latest GO.obo file but not its own term.
```
$ grep GO:0005554 go.obo
alt_id: GO:0005554
```
This prevents a term entry from being in the raw goobo_extract table that's joined to go_classification, thus preventing update of obsolescence_date. Need to add extra SQL to obsolete terms used as alt_ids in other term records.

Also should ensure that go_annotations to these obsoleted terms should be updated to use its new primary term. Example: accession=GO:0003674, alt_id=GO:0005554. Annotation should be updated to use GO:0003674.

**Comment by dustine32** [comment]
Other examples are coming in:
> 2018-06-02: GO:0042787 is alternative accession to GO:0006511 , this is a merge, so annotation to PTN000135257 is updated with primary GO accession GO:0006511.
Similar to GO:0005554, term GO:0042787 was completely deleted from go.obo so updating go_classification via a join with the extracted term list (goobo_extract) will miss obsoleting this term.

There seems to be inconsistency in how terms are obsoleted in the obo file:
- Some terms are completed deleted and their only reference will be in alt_id of another term. In this case look for the new term that has the deleted term as alt_id, then set replaced_by = new term.
- Some terms are marked “is_obsolete: true” and a replaced_by term is provided. Pipeline seems to be handling these OK (ex: GO:0000362).

@cmungall @kltm Is my interpretation of alt_id and replaced_by properties in the obo file correct here? Let me know if you want further explanation of context.

**Comment by pgaudet** [comment]
* GO:0042787  is a **merged** term; its ID becomes a secondary ID (it's not 'completely deleted').  I am not sure how you are handling this but these are *not* obsolete terms
* GO:0000362 really is obsolete. 

Would it help if you generated a list of all the alt_ids and how they map to primary ids? 

Clearly we need documentation explaining this ! 

Thanks, Pascale

**Comment by dustine32** [comment]
Thanks @pgaudet for the clarification! This explains the difference in the obo file for merged vs. obsoleted terms. I should be able to quickly get you a list of alt_ids-to-primary_ids from our DB.

For merged terms, would annotations to these terms still be valid or would they all need to be updated to their primary ID?

**Comment by pgaudet** [comment]
Ideally you would update to the primary term.

**Comment by dustine32** [comment]
Great, thanks! So we can update annotations similarly for terms that are either obsoleted or merged. But we'll need to parse these out of the ontology differently, which is fine.

**Comment by dustine32** [comment]
Running the test queries in the above commit after the late-August PAINT update show that GO:0042787 is marked obsolete (it is a "merged" term but this is just how the PAINT DB works with alt_ids) and there are zero GO annotations to the term because they were updated with the replacement term GO:0006511.
