### ISSUE TITLE
These PAINT annotations are in amigo but not in PAINT GAFs

### ISSUE THREAD

**Issue by dustine32** [pantherdb/fullgo_paint_update#19]
From email with @pgaudet 

> Can you help me trace the source of these NOT anontations for PTHR13269

![image](https://user-images.githubusercontent.com/2678599/44752437-d008f400-aacf-11e8-940f-17641d3c42e1.png)

UniProtKB:E2R293 annotated to GO:0071790, specifically. The screenshot shows annotations from 2015 so need to find out where these are coming from. Checking the gene_association.paint_other.gaf submitted from PAINT on 8/2/18 for UniProtKB:E2R293 lines, I don't see this GO:0071790 annotation or the 2015 ones:
```
UniProtKB	E2R293	NDC1		GO:0070762	PMID:21873635	IBA	PANTHER:PTN000327778|SGD:S000004493	C	Uncharacterized protein	UniProtKB:E2R293|PTN001409632	protein	taxon:9615	2017-02-28	GO_Central
UniProtKB	E2R293	NDC1		GO:0017056	PMID:21873635	IBA	PANTHER:PTN000327778|UniProtKB:Q9BTX1|SGD:S000004493	F	Uncharacterized protein	UniProtKB:E2R293|PTN001409632	protein	taxon:9615	2017-02-28	GO_Central
UniProtKB	E2R293	NDC1		GO:0006999	PMID:21873635	IBA	PANTHER:PTN000327778|SGD:S000004493	P	Uncharacterized protein	UniProtKB:E2R293|PTN001409632	protein	taxon:9615	2017-02-28	GO_Central
```

This issue may end up getting pushed up to amigo.

**Comment by dustine32** [comment]
Page from above amigo screenshot: http://amigo.geneontology.org/amigo/gene_product/UniProtKB:E2R293

**Comment by dustine32** [comment]
Amigo load details link:
http://amigo.geneontology.org/amigo/load_details

**Comment by dustine32** [comment]
With the latest load to amigo, these NOT annotations are finally gone:
![image](https://user-images.githubusercontent.com/2678599/45231532-1a813200-b281-11e8-8877-4f428638db37.png)

Looks like this is resolved?

**Comment by pgaudet** [comment]
Hurray !!!! Thank you !!
