### ISSUE TITLE
Implement taxon constraints checking

### ISSUE THREAD

**Issue by dustine32** [pantherdb/fullgo_paint_update#20]
Either report or filter taxon constraint violating annotations at time of GAF generation. Could add this check to paint_annotation [query](https://github.com/pantherdb/fullgo_paint_update/blob/master/scripts/sql/paint_annotation.sql) that feeds the GAF process.

The check would work with a lookup file generated by running a dummy GAF file (all GO terms X all taxon IDs used by PAINT) through [gaferencer](https://github.com/balhoff/gaferencer) with latest version of go-plus.owl, then filtering for all violations. Ex:
```
{
    "tuple" : {
      "taxon" : "http://purl.obolibrary.org/obo/NCBITaxon_4896",
      "annotation" : {
        "relation" : "http://purl.obolibrary.org/obo/RO_0002331",
        "term" : "http://purl.obolibrary.org/obo/GO_0009450"
      },
      "extension" : [
      ]
    },
    "inferences" : [
    ],
    "satisfiable" : false
}
```
This list of violations would be the whole lookup file. The lookup would have to get refreshed every month as the release go-plus.owl is updated.

This ticket is better described by @cmungall here:
https://github.com/geneontology/gaferencer/issues/1

**Comment by dustine32** [comment]
We have this implemented to work with the PAINT tool. Using gaferencer on go-plus.owl, the lookup table is updated every month during the monthly PAINT/GO update.

**Comment by pgaudet** [comment]
There is still some problem with taxa not being recognized - can anyone add an example?

**Comment by pgaudet** [comment]
@marcfeuermann @keslingmj

**Comment by pgaudet** [comment]
@mugitty Does the latest version of PAINT addresses this?

**Comment by mugitty** [comment]
@pgaudet, taxon constraint violations are currently not handled by the software via creation of TCV annotation or prevention of annotation creation by curator.  The feature will be enabled when the entries in the taxon constraints file are correct. For now, the software checks the entries in the file and prompts curator to create a ticket, if entry in the taxon constraints file is incorrect.

**Comment by dustine32** [comment]
@pgaudet As far as the PAINT IBA export is concerned, taxon constraints are not used to filter invalid IBAs from the GAFs. Instead, we're relying on the GO pipeline's QC checks, which also use gaferencer, to do this filtering for us.

The PAINT tool UI (I believe, @mugitty can confirm this) is currently providing to curators warnings or some other kind of feedback that _does_ check taxon constraints.

So, closing this for now but we can reopen if more work is needed.
