### ISSUE TITLE
ID part of full taxon IDs missing in GAF

### ISSUE THREAD

**Issue by kltm** [pantherdb/fullgo_paint_update#27]
As reported from Friday, and fixed in https://github.com/pantherdb/fullgo_paint_update/commit/ee25c0d40fd48a4a658af7e183e7e0d803723615
This ticket is being created to be referenced for GO code - apologies to @dustine32

**Comment by kltm** [comment]
@dustine32 Please go ahead and close this.

**Comment by dustine32** [comment]
No prob @kltm thanks!
