### ISSUE TITLE
Obsolete Uniprot entries should be filtered at each PAINT release

### ISSUE THREAD

**Issue by pgaudet** [pantherdb/fullgo_paint_update#46]
Hello, 

Following up on the April PAINT call, I asked that obsolete Uniprot entries should be filtered at each PAINT release. 

@dustine32 Please can you tell us what you'd need to do that ? 
@alexsign would you be able to give us a list of obsoleted entries so we can implement this filter ? 

Thanks, Pascale

**Comment by alexsign** [comment]
[paint_syntax_check20200426.log](https://github.com/pantherdb/fullgo_paint_update/files/4540162/paint_syntax_check20200426.log)
here we go, full report @pgaudet

**Comment by dustine32** [comment]
Thans @alexsign!

@pgaudet Should we only be filtering out IBAs to UniProtKB IDs? I couldn't find any `Unsupported / unmapped identifier` errors to UniProtKB IDs in @alexsign's report; only errors of this type were for MOD IDs like WB, MGI, FB, etc.

My initial plan was to either:
1. Call some UniProt service that will validate each UniProtKB ID before its IBA is written out.
2. Download entire UniProt ID dataset to check each IBA's UniProtKB ID against.

Not sure how feasable 1 is given that means almost 4 million API calls. Probably 2 is easier but may hit a roadblock if UnitProt dataset is super huge.

@alexsign Do you know of a public download I can grab that minimally lists all currently valid UniProt accessions?

**Comment by alexsign** [comment]
@dustine32 
I looked at the ways you can get the list of current UniProt ids, but it's not really straightforward to do. Instead, I posted the GPI file for you with all current UniProt ids here:
  
ftp://ftp.ebi.ac.uk/pub/contrib/goa/uniprot_protein.gpi.gz

If this works for you let me know and I'll make it regular posting.

**Comment by dustine32** [comment]
Thanks again @alexsign! This looks like it should work for filtering obsolete UniProt accessions but I'll do a test run to confirm and let you know.

**Comment by dustine32** [comment]
@pgaudet I was finally able to try a test run of filtering out the IBAs to these obsoleted UniProt entries. Stats report at https://docs.google.com/spreadsheets/d/1tCm_WqG0w_vj9JuC6R1xydf5FDNcAlGDuFOhZ524N3o/edit#gid=1651973446
* 81481 lines filtered out
* 19218 distinct UniProt IDs (I'll attach these below)
[filtered_ibas_obs_uniprot.txt](https://github.com/pantherdb/fullgo_paint_update/files/4654040/filtered_ibas_obs_uniprot.txt)

The base set of IBA files that I tested this filter on is the same set available at:
ftp://ftp.pantherdb.org/downloads/paint/presubmission/

Let me know if these numbers look OK and I can push the filter change to our regular pipeline.

**Comment by pgaudet** [comment]
I have no idea about numbers... can you give a couple of specific examples for a few species ? (let's say human + a few from 'other').

Thanks, Pascale

**Comment by dustine32** [comment]
@pgaudet But you're great with numbers! Here are two examples - C9JCJ5, Q5JXX5 in HUMAN:
```
UniProtKB       C9JCJ5  C9JCJ5          GO:0034213      PMID:21873635   IBA     PANTHER:PTN000789406|UniProtKB:Q15274   P       Uncharacterized protein (Fragment)      UniProtKB:C9JCJ5|PTN002425975   protein taxon:9606      20170228        GO_Central
UniProtKB       C9JCJ5  C9JCJ5          GO:0005737      PMID:21873635   IBA     PANTHER:PTN000789406|UniProtKB:P30011|RGD:1310309       C       Uncharacterized protein (Fragment)      UniProtKB:C9JCJ5|PTN002425975   protein taxon:9606      20170228        GO_Central
UniProtKB       Q5JXX5  GLRA4           GO:0007218      PMID:21873635   IBA     PANTHER:PTN001055303|UniProtKB:P23415|UniProtKB:P48167|UniProtKB:P23416 P       Glycine receptor subunit alpha-4        UniProtKB:Q5JXX5|PTN002498377   protein taxon:9606      20170228        GO_Central
UniProtKB       Q5JXX5  GLRA4           GO:0034220      PMID:21873635   IBA     PANTHER:PTN000434994|WB:WBGene00002974|WB:WBGene00000055|ZFIN:ZDB-GENE-980526-137|UniProtKB:P36544|FB:FBgn0000036|UniProtKB:Q401N2|FB:FBgn0000039|WB:WBGene00006797|UniProtKB:P23416    P       Glycine receptor subunit alpha-4        UniProtKB:Q5JXX5|PTN002498377   protein taxon:9606      20170228        GO_Central
```
Some `other` species - PIG:
```
UniProtKB       I3LDT9  PCDHA13         GO:0007155      PMID:21873635   IBA     PANTHER:PTN001932250|MGI:MGI:1338042|RGD:620504 P       Protocadherin alpha 13  UniProtKB:I3LDT9|PTN001524590   protein taxon:9823      20170228        GO_Central
UniProtKB       I3LDT9  PCDHA13         GO:0005887      PMID:21873635   IBA     PANTHER:PTN001932250|UniProtKB:Q9HBB8|MGI:MGI:2157782|MGI:MGI:1298369|MGI:MGI:2136740   C       Protocadherin alpha 13  UniProtKB:I3LDT9|PTN001524590   protein taxon:9823      20170228        GO_Central
```
Plasmodium falciparum:
```
UniProtKB       Q8IEF0  PF3D7_1316500           GO:0003723      PMID:21873635   IBA     PANTHER:PTN000221451|SGD:S000001495     F       Pre-mRNA-processing factor 40, putative UniProtKB:Q8IEF0|PTN000933501   protein taxon:36329     20170228        GO_Central
UniProtKB       Q8IEF0  PF3D7_1316500           GO:0005685      PMID:21873635   IBA     PANTHER:PTN000221451|PomBase:SPAC4D7.13|SGD:S000001495  C       Pre-mRNA-processing factor 40, putative UniProtKB:Q8IEF0|PTN000933501   protein taxon:36329     20170228        GO_Central
```

**Comment by pgaudet** [comment]
Looks great !!!! 
Please implement that :) 

Thanks, Pascale

**Comment by dustine32** [comment]
@alexsign I was able to get your GPI working in the IBA pipeline. Hooray! However, when I spot-checked a few of the human IBAs that were filtered out due to their IDs missing in the GPI, I am still able to see them on the UniProt site. Some examples:
Q95604
A0A0A6YYH2
P01891
Q31612
Q95604
Should these be in the GPI available at ftp://ftp.ebi.ac.uk/pub/contrib/goa/uniprot_protein.gpi.gz?

**Comment by alexsign** [comment]
@dustine32 the entry you listed in on the UniProt website right now, but they would be removed in the next public release this June 17th. I usually provide UniProt/GOA private data to our collaborators, so they are in sync or ahead on the checks.

**Comment by dustine32** [comment]
@alexsign Ah, cool, sneak preview! Great, this should work then.

BTW, how often will this GPI be updated? Monthly? Quarterly? Just curious.

**Comment by alexsign** [comment]
@dustine32 the data generated weekly, most of the time :). But, it's not updated weekly, because uniprot data in not updated that often. I will post it weekly as well, but your checks doesn't have to be run weekly.

**Comment by dustine32** [comment]
Thanks @alexsign !

**Comment by pgaudet** [comment]
@dustine32 If this is implemented, can we close the ticket? 

Thanks, Pascale

**Comment by dustine32** [comment]
@pgaudet Good call, thank you!
