### ISSUE TITLE
Check validity of with/from field components

### ISSUE THREAD

**Issue by dustine32** [pantherdb/fullgo_paint_update#6]
From Tony's QA checks:
https://github.com/geneontology/go-annotation/issues/2044#issuecomment-410964058

Number of annotations with invalid with/from components: 381373
ECO:0000318 (IBA) - valid entity types: CHEBI:33697 (ribonucleic acid) or NCIT:C20130 (protein family) or PR:000000001 (protein) or SO:0000704 (gene)
TAIR [BET:0000000 (communication) or SO:0000185 (primary transcript) or SO:0000704 (gene)]: 380720
WB [PR:000000001 (protein) or SO:0000704 (gene) or VariO:0001 (variation)]: 653

**Comment by dustine32** [comment]
Apparently these two WB identifiers are being flagged as invalid:
WB:F09E5.15c
WB:F52H2.2b

These do look different from other WB IDs, which follow the WB:WBGene00000466 format.

**Comment by pgaudet** [comment]
Looks like something got mixed up - it's the gene name: 

https://wormbase.org/species/c_elegans/gene/WBGene00017283

Any idea what's the source of the problem ? 

Thanks, Pascale

**Comment by dustine32** [comment]
Yeah, not sure exactly what happened. The long ID in Panther is:
CAEEL|WormBase=F09E5.15c|UniProtKB=A0A0K3AUJ9

Checking this year's C. ele reference proteome set, the WBGene00006434 ID is in there. I'm wondering if this was manually added to Panther?

**Comment by pgaudet** [comment]
That's a question for @huaiyumi and @thomaspd I guess

**Comment by dustine32** [comment]
@pgaudet Closing since both issues in this ticket have since been fixed:

1. `TAIR:locus:` IDs in the with/from field are now accepted by the QC checks.
2. Those two WB IDs have been fixed in the latest PANTHER version 17.0:
    1. `CAEEL|WormBase=F09E5.15c|UniProtKB=A0A0K3AUJ9` is now `CAEEL|WormBase=WBGene00006434|UniProtKB=A0A0K3AUJ9`
    2. `CAEEL|WormBase=F52H2.2b|UniProtKB=A0A0K3AVL7` is now `CAEEL|WormBase=WBGene00000004|UniProtKB=A0A0K3AVL7`

**Comment by pgaudet** [comment]
Thanks!
