### ISSUE TITLE
IBA GAF creation should output species taxon for S. pombe

### ISSUE THREAD

**Issue by dustine32** [pantherdb/fullgo_paint_update#60]
PAINT IBA GAF lines using the Schizosaccharomyces pombe strain taxon 284812 are causing [issues](https://github.com/geneontology/go-releases/issues/77) [downstream](https://github.com/geneontology/helpdesk/issues/468). PANTHER currently stores the strain taxon because that is what was supplied by Reference Proteome at the time of building the library. Rather than changing this taxon data in PANTHER internally, we'll treat the IBA GAFs as sort of an "export" file and transform the output taxon to be the species taxon 4896.

For now, we will just do this for _S. pombe_ and hard-code the strain -> species taxon transformation. I can do a special IBA GAF release to get this out soon. Later, we could expand this function to apply to more (if not all) PANTHER genomes and utilize the NCBI taxonomy ontology to traverse up to species-level taxa.

Tagging @pgaudet @thomaspd @huaiyumi @kltm @vanaukenk

**Comment by kltm** [comment]
https://github.com/orgs/geneontology/projects/62#card-92270179

**Comment by dustine32** [comment]
Closing as completed because this change is now in the 2024-04-09 PAINT IBA release [files](http://data.pantherdb.org/ftp/downloads/paint/17.0/2024-04-09/).
