### ISSUE TITLE
Fix IBA GAF format issues

### ISSUE THREAD

**Issue by dustine32** [pantherdb/fullgo_paint_update#7]
From email from @pgaudet :

4. Format issues: 
4.1 Date should be YYYYMMDD (no dash)
4.2 Qualifiers ‘COLOCALIZES_WITH’ and ‘CONTRIBUTES_TO’ shoud be small case
4.3 For entries with no Gene name, column 3 (DB Object Symbol) should repeat the identifier (for e.g.: U3KQV3) 

These will need to be fixed in the createGAF.pl script.

**Comment by pgaudet** [comment]
Great ! let me know when it's done.

Pascale

**Comment by dustine32** [comment]
@pgaudet Looks like all three issues are taken care of when generating the latest batch of IBA GAFs:

UniProtKB:U3KQV3 example line from 8/2/18:
```
UniProtKB	U3KQV3		COLOCALIZES_WITH	GO:0005886	PMID:21873635	IBA	PANTHER:PTN000632672|UniProtKB:A0A1D8PH96|MGI:MGI:107949|PomBase:SPAC23C4.08|MGI:MGI:106028|SGD:S000001763|CGD:CAL0000192659|UniProtKB:Q92730|UniProtKB:P62745|MGI:MGI:1096342	C	Uncharacterized protein (Fragment)	UniProtKB:U3KQV3|PTN001938688	protein	taxon:9606	2017-05-03	GO_Central
```
Today's run:
```
UniProtKB	U3KQV3	U3KQV3	colocalizes_with	GO:0005886	PMID:21873635	IBA	PANTHER:PTN000632672|UniProtKB:A0A1D8PH96|MGI:MGI:107949|PomBase:SPAC23C4.08|MGI:MGI:106028|SGD:S000001763|CGD:CAL0000192659|UniProtKB:Q92730|UniProtKB:P62745|MGI:MGI:1096342	C	Uncharacterized protein (Fragment)	UniProtKB:U3KQV3|PTN001938688	protein	taxon:9606	20170503	GO_Central
```
4.1 Date's in YYYYMMDD format
4.2 "colocalizes_with" is lowercased.
4.3 Identifier for GP with no symbol is repeated in col 3.

**Comment by kltm** [comment]
@pgaudet Hopefully, that would depend on when the latest PAINT GAFs were released.
If after the last `release` cycle, the `current` reports would reflect the state of the upstream GAFs at that time.
Interestingly, the `snapshot` (yesterday) also has these: http://current.geneontology.org/reports/dictybase-report.html, which might be a bit worrying.
@dustine32 When did this latest batch come out? I can see that you are fine at the source.

**Comment by dustine32** [comment]
@pgaudet @kltm I guess I only expected the changes to so far trickle through the `snapshot` run, since the "fixed" batch of PAINT GAFs was uploaded late last night ~10:20pm PST. Specifically, the `snapshot` run that started midnight last night and is probably still running?

**Comment by kltm** [comment]
@dustine32 You are correct--the "correct" reports then should be available on snapshot in about 12hrs.

**Comment by dustine32** [comment]
@cmungall Now it is! Just confirmed that the example annotation came through the GO pipeline this month the the changes in place:
```
$ grep U3KQV3 goa_human.gaf | grep GO:0005886
UniProtKB	U3KQV3	U3KQV3	colocalizes_with	GO:0005886	PMID:21873635	IBA	CGD:CAL0000192659|MGI:MGI:106028|MGI:MGI:107949|MGI:MGI:1096342|PANTHER:PTN000632672|PomBase:SPAC23C4.08|SGD:S000001763|UniProtKB:A0A1D8PH96|UniProtKB:P62745|UniProtKB:Q92730	C	Uncharacterized protein		protein	taxon:9606	20170503	GO_Central
```
BTW I assigned it to @huaiyumi because he made the actual changes to the GAF generation script, though I committed his changes to run them in the pipeline. Thanks!
