### ISSUE TITLE
Extra annotation for lines with colocalizes_with

### ISSUE THREAD

**Issue by dustine32** [pantherdb/fullgo_paint_update#8]
From email from @pgaudet 

3. Two annotations, with and without colocalizes_with, are still present  
Q9BYB0	SHANK3	COLOCALIZES_WITH	GO:0005886
Q9BYB0	SHANK3		GO:0005886

@pgaudet I'm guessing the line missing the "COLOCALIZES_WITH" (soon to be lowercase-d) needs to be removed?

**Comment by pgaudet** [comment]
Hi @dustine32 

The original ticket is here: https://github.com/geneontology/go-annotation/issues/2019
Yes please remove the COLOCALIZES_WITH annotation. 

Can you check if there are other cases like this ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
and with other qualifiers. PAINT should not produce annotations that differ only by the presence/absence of the qualifier.  

Pascale

**Comment by pgaudet** [comment]
Fixed. Possibly manually by @huaiyumi
